# site.[]
url: "https://awarei.github.io/BugHunt"
baseurl: "/BugHunt"
project: "BugHunt"
author: awarei
title:  BugHunt

theme: minima
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

collections:
  reports:
    output: true
    permalink: /reports/:title
