# site.[]
url: "https://awarei.github.io/BugHunt"
project: "BugHunt"
author: awarei
title:  BugHunt

markdown: kramdown
permalink: /BugHunt/blog/:year/:month/:day/:title

collections:
  reports:
    output: true
    permalink: /BugHunt/reports/:title
