# site.[]
url: "https://awarei.github.io/BugHunt"
author: awarei
title:  BugHunt

markdown: kramdown
permalink: /BugHunt/blog/:title

collections:
  reports:
    output: true
    permalink: /BugHunt/reports/:title
